=== cleancoderocker/schroedinger-programmiert-java/SchroedingerProgrammiertJava/resources/kapitel14/musiksammlung.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:ms="http://www.rheinwerk-verlag.de/schroedinger/musiksammlung"
	targetNamespace="http://www.rheinwerk-verlag.de/schroedinger/musiksammlung"
	elementFormDefault="qualified">
	<element name="musiksammlung">
		<complexType>
			<sequence>
				<element name="kuenstler" type="ms:kuenstler" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="kuenstler">
		<sequence>
			<element name="name" type="string" />
			<element name="alben" type="ms:alben" />
		</sequence>
	</complexType>
	<complexType name="alben">
		<sequence>
			<element name="album" type="ms:album" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	<complexType name="album">
		<sequence>
			<element name="veroeffentlicht" type="int" maxOccurs="1"/>
		</sequence>
		<attribute name="titel" type="string" />
	</complexType>
</schema>

=== cleancoderocker/schroedinger-programmiert-java/SchroedingerProgrammiertJava/resources/kapitel14/musiksammlung4.xml
<?xml version="1.0" encoding="UTF-8"?>
<musiksammlung
	xmlns="http://www.rheinwerk-verlag.de/schroedinger/musiksammlung"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rheinwerk-verlag.de/schroedinger/musiksammlung musiksammlung.xsd">
	<kuenstler>
		<name>Jimi Hendrix</name>
		<alben>
			<album titel="Are You Experienced">
				<veroeffentlicht>1967</veroeffentlicht>
			</album>
			<album titel="Electric Ladyland">
				<veroeffentlicht>1968</veroeffentlicht>
			</album>
		</alben>
	</kuenstler>
	<kuenstler>
		<name>The Beatles</name>
		<alben>
			<album titel="The BEATLES">
				<veroeffentlicht>1968</veroeffentlicht>
			</album>
			<album titel="Yellow Submarine">
				<veroeffentlicht>1969</veroeffentlicht>
			</album>
		</alben>
	</kuenstler>
	<kuenstler>
		<name>Deep Purple</name>
		<alben>
			<album titel="Shades of Deep Purple">
				<veroeffentlicht>1968</veroeffentlicht>
			</album>
			<album titel="Deep Purple in Rock">
				<veroeffentlicht>1970</veroeffentlicht>
			</album>
		</alben>
	</kuenstler>
</musiksammlung>

=== cleancoderocker/schroedinger-programmiert-java/SchroedingerProgrammiertJava/resources/kapitel14/musiksammlung.xml
<?xml version="1.0" encoding="UTF-8"?>
<musiksammlung
	xmlns="http://www.rheinwerk-verlag.de/schroedinger/musiksammlung"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rheinwerk-verlag.de/schroedinger/musiksammlung musiksammlung.xsd">
	<kuenstler>
		<name>Jimi Hendrix</name>
		<alben>
			<album titel="Are You Experienced">
				<veroeffentlicht>1967</veroeffentlicht>
			</album>
			<album titel="Electric Ladyland">
				<veroeffentlicht>1968</veroeffentlicht>
			</album>
		</alben>
	</kuenstler>
</musiksammlung>
