=== cleancoderocker/schroedinger-programmiert-java/SchroedingerProgrammiertJava/resources/kapitel14/terminkalender.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tk="http://www.rheinwerk-verlag.de/schroedinger/terminkalender"
	targetNamespace="http://www.rheinwerk-verlag.de/schroedinger/terminkalender"
	elementFormDefault="qualified">
	<element name="terminkalender">
		<complexType>
			<sequence>
				<element name="besitzer" type="tk:besitzer" />
				<element name="termine" type="tk:termine" />
			</sequence>
		</complexType>
	</element>
	<complexType name="besitzer">
		<sequence>
			<element name="name" type="string" />
		</sequence>
	</complexType>
	<complexType name="termine">
		<sequence>
			<element name="termin" type="tk:termin" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" />
	</complexType>
	<complexType name="termin">
		<sequence>
			<element name="was" type="string" />
			<element name="wann" type="string" />
			<element name="wo" type="string" />
		</sequence>
	</complexType>
</schema>

=== cleancoderocker/schroedinger-programmiert-java/SchroedingerProgrammiertJava/resources/kapitel14/terminkalender.xml
<?xml version="1.0" encoding="UTF-8"?>
<terminkalender
	xmlns="http://www.rheinwerk-verlag.de/schroedinger/terminkalender"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.rheinwerk-verlag.de/schroedinger/terminkalender terminkalender.xsd">
	<besitzer>
		<name>Schrödinger</name>
	</besitzer>
	<termine name="Meine Termine">
		<termin>
			<was>Katze füttern</was>
			<wann>8:00</wann>
			<wo>Küche</wo>
		</termin>
		<termin>
			<was>Mit Freundin Schuhe einkaufen</was>
			<wann>9:00</wann>
			<wo>Schuhgeschäft</wo>
		</termin>
		<termin>
			<was>WoW spielen</was>
			<wann>20:00</wann>
			<wo>Am Computer</wo>
		</termin>
	</termine>
</terminkalender>

=== cleancoderocker/schroedinger-programmiert-java/SchroedingerProgrammiertJava/resources/kapitel14/terminkalender_geaendert.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<terminkalender xmlns="http://www.rheinwerk-verlag.de/schroedinger/terminkalender" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.galileocomputing.de/schroedinger/terminkalender terminkalender.xsd">
	<besitzer>
		<name>Schrödinger</name>
	</besitzer>
	<termine name="Meine Termine">
		<termin>
			<was>Katze füttern</was>
			<wann>8:00</wann>
			<wo>Küche</wo>
		</termin>
		<termin>
			<was>Mit Freundin Schuhe einkaufen</was>
			<wann>9:00</wann>
			<wo>Schuhgeschäft</wo>
		</termin>
		<termin>
			<was>WoW spielen</was>
			<wann>20:00</wann>
			<wo>Am Computer</wo>
		</termin>
	<termin>
      <was>Mit DOM-API Musiksammlung von deiner Freundin als XML-Dokument erstellen.</was>
      <wann>Sofort</wann>
      <wo>Werkstatt</wo>
    </termin>
  </termine>
</terminkalender>
